### ISSUE TITLE
telegram username add button disappeared suddenly

### ISSUE THREAD

**Issue by paneda1998** [grafana/oncall#1046]
Hi
I have problem for adding telegram account for users in user tab grafana oncall 
![image](https://user-images.githubusercontent.com/52179148/209685009-24ff430c-53c4-42de-b498-2f53ab5d8ff6.png)
at you see in this pic
there is no way for adding telegram username for users

I think. this is a UI bug
because when i send some curl request to backend that works fine.

**Comment by raphael-batte** [comment]
Hi! Usually it happens when user has **viewer** permissions. What level of permissions does the user have in this case?

**Comment by paneda1998** [comment]
I check for both viewer and admin users. no difference.
i hame this problem for all users in all teams!

**Comment by raphael-batte** [comment]
Thanks for the feedback! Marked issue as bug.

**Comment by alexintech** [comment]
User can add telegram connection only by himself. See [here](https://github.com/grafana/oncall/blob/62a42438e56a59a953e9bc893685821d195e18c8/grafana-plugin/src/containers/UserSettings/UserSettings.tsx#LL55C1-L55C1). That makes sense, because for each user individual token generates.

@paneda1998 can you connect your personal user account?

**Comment by joeyorlando** [comment]
Going to close as we haven't received more info to reproduce. Please feel free to reopen if you're still seeing this issue!
