### ISSUE TITLE
Integration settings drawer randomly opens back

### ISSUE THREAD

**Issue by maskin25** [grafana/oncall#1083]
more details https://raintank-corp.slack.com/archives/C0229FD3CE9/p1672903035392769

**Comment by thomasmitchell** [comment]
This appears to happen when steps of an escalation chain for the current integration are still loading when you navigate away - when that network call returns, it will go back to the integrations screen. This is particularly common for us at this point because our Manual Incidents integration (the one that's loaded by default when going to the Integrations page) now has quite a lot of routes in order to facilitate the Slack slash command, and therefore, once you've gone to the Integrations page, you need to wait 5-10 seconds before navigating away or else you'll get snapped right back.
