### ISSUE TITLE
Rename or Description for Schedules Rotations

### ISSUE THREAD

**Issue by Mazizieh** [grafana/oncall#1460]
In Grafana Oncall, cloud and I beleive open source version as well, there is no way to rename or add a description for Schedules Rotations. 

Added rotations are having default names like L-1-1 and those a names can't be changed or at least having a description, like a GMT rotation or anything else. 
[
![Grafana](https://user-images.githubusercontent.com/51692140/223103633-9df8fe28-5ccf-4f2e-89a0-b85a460e510a.png)
](url)

**Comment by Konstantinov-Innokentii** [comment]
Moved to "in progress", since web and terraform uses different name fields which will lead to confusion. Ideally we want to show name from terraform in web and most importantly do not have two sources of truth for actual shift title.

**Comment by Konstantinov-Innokentii** [comment]
Opened a [PR](https://github.com/grafana/oncall/pull/1833) with backend. 
Now shift has a "name" field. When it's null frontend can show some default name (L**x**-**y** Rotation), but send new name value if user modifies it.
It is done because there is  no way of defining **y** in "L**x**-**y** Rotation"  on backend while migrating. 
However, I'm not sure how frontend calculates **y**, going to discuss it with @maskin25 when he will be back from PTO.
