### ISSUE TITLE
Slack notifications not displaying properly on mobile

### ISSUE THREAD

**Issue by mderynck** [grafana/oncall#167]
On mobile notifications from slack show contents as "This content can't be displayed".

A similar issue: 
https://github.com/grafana/grafana/issues/42768
was fixed in Grafana with this PR:
https://github.com/grafana/grafana/pull/45750

We likely need to pass through and add a top level text field to the slack messages we are sending where it is missing.

**Comment by skeilson** [comment]
@mderynck we have at least 2 reports of this problem. Is there any update on this and if not, could an ETA be provided?

**Comment by Matvey-Kuk** [comment]
@skeilson this issue is not in the short-term backlog yet. Will let you know once we have any updates. 

Any contributors willing to fix this are very welcome!

**Comment by Bahus** [comment]
> this issue is not in the short-term backlog yet

@Matvey-Kuk this confuses me a lot. 

As far I remember slack always was a paramount integration in amixer/grafana on call, so it's very strange to hear that most of the product users (especially paying ones) still have to click on a notification to open slack and see full alert message. Same on a phone and a desktop.

It's very very annoying, counterproductive and (from my point of view) unacceptable for a paid service.

In addition I don't think this going to be an easy fix, since a title can include text, links, markup, can be shot/long etc, so it will require some testing on desktop/mobile devices and I'm sure one have to make some compromises.

**Comment by rs** [comment]
Agreed. As a paying customer, this is making oncall barely usable and very inconvenient.

I would suggest a special field to set the notification text in the oncall configuration UI.

**Comment by iskhakov** [comment]
We decided to prioritize this bugfix, thanks for the feedback. 
It's in our short-term backlog now

**Comment by iskhakov** [comment]
We were able to reproduce the issue on the android devices. On ios and on the desktop push notifications were able to display the information about the alert. We'll apply the hotfix soon and will consider adding the separate optional template to configure the text you see in the push notification

**Comment by rs** [comment]
We can definitely reproduce the issue on iOS and macOS.

**Comment by Matvey-Kuk** [comment]
@mderynck 🎉
