### ISSUE TITLE
When creating a new schedule rotation layer the default date should be today

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#2011]
When adding a new schedule rotation layer, it appears that the modal defaults to Monday of the current week. I tried adding a rotation on Wednesday May 24, and the default rotation start date was Monday May 22. imo it should default to the current datetime

<img width="760" alt="Screenshot 2023-05-24 at 19 59 10" src="https://github.com/grafana/oncall/assets/9406895/60523245-ed78-423d-802a-92e7f1882a0f">

**Comment by matiasb** [comment]
I think this was decided on the fact that it is useful to get the rotation started on (first day of the week) because you usually define a weekly pattern you want to repeat, and then you get a quick preview for that. I would keep that default behavior when adding a rotation layer through buttons.

Note you could start a rotation on a specific day by clicking on the correspondent day, although this only works for the first layer. Maybe we could make it possible to click on the day header to start a new rotation from that date too?
