### ISSUE TITLE
Slack notification links are wrong

### ISSUE THREAD

**Issue by naten3** [grafana/oncall#2221]
I have an Open Source Oncall setup deployed using helm.

The slack notification links are incorrect. They are pointing to the name of our kubernetes pod, eg `release-oncall-grafana/a/grafana-oncall-app/etc`

Looking through the code, I think the url is coming the from the database value  `user_management_organization.grafana_url` , which I don't believe I can change (changing to `{my public url}/grafana` caused other issues)
Is there any way to override this? Thank you.

**Comment by naten3** [comment]
I don't seem to have the permissions to add a lable. 

part:alertflow
bug

**Comment by joeyorlando** [comment]
@naten3 apologies for that. we're experimenting with some different GitHub workflows at the moment.

**Comment by mderynck** [comment]
Generally OnCall should be configured so that the `grafana_url` used to reach Grafana is the same as the public URL used from slack or anywhere else to reach the Grafana instance. 

If that doesn't work you can override only in slack by modifying your Integration template.  In the Integration configuration (Gear Icon), Edit template for -> Slack.

Somewhere in the Title template there should be:
`{{ grafana_oncall_link }} `
You can try this instead:
`{{ grafana_oncall_link | replace("release-oncall-grafana","my public url/grafana") }} `

**Comment by Matvey-Kuk** [comment]
Looks like @mderynck shared a solution so closing :)
