### ISSUE TITLE
Formally validate SLACK_INSTALL_RETURN_REDIRECT_HOST

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#229]
We can't validate SLACK_INSTALL_RETURN_REDIRECT_HOST on the Slack's side in a background. Anyway users sometimes misconfigure and it's hard to debug:

<img width="676" alt="Screenshot 2022-07-13 at 14 39 15" src="https://user-images.githubusercontent.com/3284841/178725246-2a7fd7cb-1fa6-457d-b264-50c270e77ef0.png">

What if we make at least formal validation on our side for `https://` in the beginning and training slashes `/` (not sure if they are required or not btw)?

Could be also useful for:
- `TELEGRAM_WEBHOOK_HOST`

I guess it will help users to avoid such problems in the future.

**Comment by mInrOz** [comment]
Easy mistake that can be made, as variable only specifies HOST.
Not necessarily clear that you need to include the protocol used as well, especially since I assume HTTPS is the only one valid.

Not a huge issue, but If I ran into this. There is probably bound to be others who have the same mindset/thought as I do.
If its not specified, Slack nor the OnCall Plugin gives any meaningful error code. Only a generic error.

**Comment by mderynck** [comment]
https://github.com/grafana/oncall/pull/280 takes care of the trailing slash, still need to validate for protocol.

**Comment by vadimkerr** [comment]
This should be now fixed by https://github.com/grafana/oncall/pull/307
