### ISSUE TITLE
Add the ability to acknowledge all my alerts

### ISSUE THREAD

**Issue by terraboops** [grafana/oncall#2618]
### What would you like to see!

We had a situation where 200+ alerts fired, making it difficult to ack all the alerts during triage. It is possible and fairly straightforward in the Web UI to ack all, but I couldn't figure out mobile app.

We may be able to use alert grouping for future incidents, but it would be nice to be able to ack all alerts in cases where alert grouping is not or cannot be used.

I'd like to be able to acknowledge all unacknowledged alerts in an alert group assigned to my on call shift with no more than 3 button presses.

### Product Area

Mobile App

**Comment by Dieterbe** [comment]
@raphael-batte ?

**Comment by robert-northmind** [comment]
Hi @terraboops , we have added this feature now :D it will be shipped in the next version of the app. 
hopefully it will be available as Beta in the next days.
Here is a preview of how it looks like

https://github.com/grafana/oncall/assets/59053438/0d9b0703-def2-46f3-b6a4-50e22700f4d4

**Comment by robert-northmind** [comment]
It was fixed by this PR https://github.com/grafana/oncall-mobile-app/pull/678

**Comment by robert-northmind** [comment]
Hey @Warlord-K 
The mobile app doesn't offer a way to acknowledge all alerts since it is a bit tricky on mobile.
In the web, you can select all alert groups, and then choose to Ack them. But in web we have pagination.
so you can easily get an overview of all alert groups. So you know which ones you are calling "Ack" on.

But in mobile, you cannot easily see an overview of all Alert Groups that is loaded.
and as soon as you scroll down, we directly load in more (one more page) into the list.
So if we would enable a "Select All" option, it would be very tough to see which AlertGroups actually got selected.

That is why we didn't add the "Select All". And instead you need to manually selected them once you enter "bulk edit" mode.
But we added this topic to our backlog to discuss if there is some other way we could solve it in the app.
