### ISSUE TITLE
service account token with given name already exists in the organization

### ISSUE THREAD

**Issue by curly3031** [grafana/oncall#2754]
### What went wrong?

**What happened**:
my grafana cant connect to oncall engine after "Remove current configuration"

**What did you expect to happen**:
i have 409 error for reconnect oncall with body
message
: 
"service account token with given name already exists in the organization"
messageId
: 
"serviceaccounts.ErrTokenAlreadyExists"
statusCode
: 
400
traceID
: 
""

### Grafana OnCall Version

v1.2.34

**Comment by mderynck** [comment]
The only way I was able to recreate this (Grafana 9.5.7 & OnCall v1.2.34) was if I had an already existing OnCall API key and then used the convert to service accounts functionality in settings, then removed the configuration for OnCall and tried adding again.
This could be resolved by manually deleting the converted service account since it created an API key named OnCall which clashed with the config process when you enter the URL

This process was much improved after OnCall v1.3.2 overhauled how service accounts and API keys are used by OnCall.  I tested the scenario with the latest (Grafana 9.5.7 and OnCall v1.3.26) and could not recreate the issue.  I recommend updating since this issue is resolved in newer versions of OnCall.
