### ISSUE TITLE
Allow specifying a Redis db number

### ISSUE THREAD

**Issue by itspngu** [grafana/oncall#2764]
### What would you like to see!

Currently, the Redis db used by Oncall is [hardcoded as 1](https://github.com/grafana/oncall/blob/a1a9e0c33c0c2fe5a78e68af3409dcc3ce9d5f1c/engine/settings/base.py#L188). It would be nice if this was configurable, allowing users to safely re-use the same Redis deployment across multiple GrafanaLabs products (Grafana, Oncall, Loki, etc.) in smaller setups.

How it's done in Loki: https://grafana.com/docs/loki/latest/configuration/#cache_config
How it's done in Grafana: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#remote_cache

### Product Area

Other

**Comment by MrEcco** [comment]
There are actually two Redis databases in use: 0 (broker) and 1 (cache). But it is possible to run the whole application in a single number, celery and cache don't conflict (due to different types of keys and different naming).

@itspngu I've prepared PR (https://github.com/grafana/oncall/pull/3029) with the fix. Could you please leave a comment or like in there, just to get maintainers' attention?
