### ISSUE TITLE
Mobile: list filter support + search

### ISSUE THREAD

**Issue by imtoori** [grafana/oncall#3065]
We just added dynamic filter support. 
We still need to add support for filters with paged filter options.
For example in case of alert groups:

'integration'
'escalation_chain'
'acknowledged_by'
'resolved_by'
'silenced_by'
'invitees_are'
'involved_users_are'

In these cases we need to be able to show a paged list of filter options and we need a search field within the list

![Image](https://github.com/grafana/oncall/assets/20601437/f63f59ae-6c46-4b2c-8e75-05b5725a73fe)

note that the design is using the wrong example (team is not a searchable/paged filter option)

**Comment by pkramme** [comment]
@imtoori I believe this broke something for me. If my filter just says "Status: acknowledged" and "Status: firing", i do not see any acknowledged issues anymore. Also, sometimes the "Alert groups/Mine" overview loads forever. I cannot exactly pinpoint when this started, but it was in the last two weeks. 

I've updated grafana oncall to the latest version, but the issue is still there. I see firing events, but not any acknowledged events.

**Comment by imtoori** [comment]
hey @pkramme thanks a lot for reporting the issue!
 
Never seen this honestly, but I'll try to understand what's going on...
Have you tried completely removing the filters? You still don't see any acked alerts? Can you also confirm you see them in the web ui?
Also, just in case, maybe try uninstalling and reinstalling the app. I want to exclude any issues with persisted data.

**Comment by imtoori** [comment]
I think I managed to reproduce the issue, I'll let you know asap

**Comment by imtoori** [comment]
Good news, I found the bug and I'll release a version as soon as possible! Thanks a lot for reporting the issue!

**Comment by imtoori** [comment]
Thank you for reporting the bug!!! 
Opening an issue in this repo is the best option :) 
Also we have an email dedicated to that mobile-support@grafana.com
