### ISSUE TITLE
Default values for ingress annotations in helm chart conflicts with cluster issuers and custom nginx ingress classes

### ISSUE THREAD

**Issue by spohner** [grafana/oncall#3069]
### What went wrong?

**What happened**:
Tried to install Grafana OnCall with Helm into our existing infrastructure. Added annotations on the ingress to account for our cluster-issuer and custom nginx ingress class. Did not include cert-manager or nginx ingress controller in the helm template as this is already present in our cluster. Got error messages on install as issuer and cluster-issuer annotations cannot co-exist.  The default value for ingressClassName annotation is also problematic if you want to use custom ingressClassName.

**What did you expect to happen**:
- Helm install to successfully complete.

### How do we reproduce it?

1. Install the helm chart with an `cert-manager.io/cluster-issuer: "custom"` annotation in the ingress and with cert-manager and nginx ingress controller disabled.
3. Observe error messages when installing.

### Grafana OnCall Version

v1.3.38

### Product Area

Helm

### Grafana OnCall Platform?

Kubernetes

### Anything else to add?

Would be happy to help with a PR. But need input on how to handle this.

Options:
1. Remove default values for ingress annotations
2. Only add the default values for the issuer and nginxClassName annotations if cert-manager and nginx ingress controller is enabled respectively.

**Comment by git4fred** [comment]
Just comment the values in values.yaml file.

**Comment by joeyorlando** [comment]
@spohner and if you trying updating `ingress.annotations` in your `values.yaml` file (or via `--set`)? This should solve your issue I believe.

**Comment by init-penguin** [comment]
I'm having similar issues with `cert-manager.io/issuer` annotation on 1.3.62 Helm release. 

Regretfully, i'm using Grafana Tanka to actually deploy OnCall on Kubernetes, so I have no way (since the chart itself is vendored) to fix that manipulating values.yaml file. 
The other option, however quite painful one, is to fork the entire chart, but updating will become a nightmare.

@spohner have you managed to fix that issue for yourself?

**Comment by spohner** [comment]
Apologies for the delayed response. After revisiting the issue, I'm currently unable to reproduce the reported issue. Overriding the default values is functioning as commented and expected. I'm uncertain about the earlier difficulties I faced in overwriting the defaults.

I appreciate all the assistance and feedback. Consequently, I will be closing this task. Thank you.

**Comment by cyberveseli** [comment]
Hello,

I had the same problem as it's explained in the first message.
This is my helm values.tftpl file:
`# Enable ingress object for external access to the resources
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
  labels:
    app: "grafana-oncall"
  tls:
    - hosts:
        - "${grafana_oncall_domain_name}"
      secretName: grafana-oncall-ingress-tls`
      
Once i deployed it, i got ingress object with default annotations too:
`Annotations:                 cert-manager.io/cluster-issuer: letsencrypt
                                       kubernetes.io/ingress.class: nginx
                                       cert-manager.io/issuer: letsencrypt-prod`
                                       
 And error was:
 `Could not determine issuer for ingress due to bad annotations: both "cert-manager.io/issuer" and "cert-manager.io/cluster-issuer" may not be set`
 
 I solved it by putting default values to _null_
 Example:
 `cert-manager.io/issuer: null`
 
 @joeyorlando Is there any chance to remove default annotations from the helm template?
 
 Thanks a lot!

**Comment by joeyorlando** [comment]
@cyberveseli have you tried the suggestion in [this comment](https://github.com/grafana/oncall/issues/3069#issuecomment-1781836402)?
