### ISSUE TITLE
Error Log Timeline in grafana Oncall web

### ISSUE THREAD

**Issue by msaitool** [grafana/oncall#3138]
### What went wrong?

**What happened**:
- When I modify the Escalation chain, the timeline log in Grafana Oncall web does not update. It remains unchanged from the previous Escalation chain. This makes it difficult for administrators to track logs in Grafana Oncall.

**What did you expect to happen**:
- When modify the Escalation chain, the timeline log in Grafana Oncall web  will update.

### How do we reproduce it?

1. Open Grafana OnCall and do X
2. Now click button Y
3. Wait for the browser to crash. Error message says: "Error..."

### Grafana OnCall Version

v 1.3.40

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

Kubernetes

### User's Browser?

Google Chrome

**Comment by mderynck** [comment]
Logs in alert groups won't change since they log what happened during the escalation.  An alert group gets a snapshot of an escalation chain at the time it starts and won't be affected by changes made after that point.  The changes to the escalation chain will affect alert groups created after the change.
