### ISSUE TITLE
ack_url_post and ack_url_get don't work

### ISSUE THREAD

**Issue by iskhakov** [grafana/oncall#371]
* check and fix ack_url_post and ack_url_get parameters
* add this feature to the documnetation and highlight in the interface

**Comment by Matvey-Kuk** [comment]
@iskhakov do we want to add them? Shouldn't it be a feature for a webhook?

**Comment by Matvey-Kuk** [comment]
`ack_url_post` and `ack_url_get` are optional payload paramethers which used to exist in the product before oficial release. I think we shouldn't bring this feature back because:
1) Processing payload paramethers without templating is breaking the concept of "render everything using Jinja" we have. Those paramethers were hardcoded which means if the payload source is not able to form the proper link, the user can't adjust it on the OnCall side.
3) It's making Webhooks feature not as straightforward. We have "Webhooks" page, it may be not easy to understand that some webhooks are generated because of "magic" paramethers in the alert payload.

What I suggest:

Think of some way to let users issue webhooks not only as an escalation step but also according to events which happened with Alert Group such as (New registered, new alert came, acked, resolved, snoosed), improve the page we have now:
<img width="1552" alt="Screenshot 2022-08-16 at 16 49 30" src="https://user-images.githubusercontent.com/3284841/184896270-ecf11376-c9a4-4be3-9c34-98bbe6e7fcc9.png">

**Comment by iskhakov** [comment]
Nice idea, I'm agree, we need to give the users ability to trigger outgoing webhooks based on the different events, such as `incident acknowledged`, `incident resolved`, also we can allow using outgoing webhooks in the personal notifications.

**Comment by Matvey-Kuk** [comment]
Personal notifications is a great idea! It will increase OnCall's apllicability a lot.

**Comment by iskhakov** [comment]
* we need to add get method to the outgoing webhooks
* we need to allow using json as a field (right now ninja converts it into string)

**Comment by tommysitehost** [comment]
This feature would be great. Would be good to be able to specify which alerts can trigger the webhook (e.g. alerts that have a specific label can trigger a webhook).

**Comment by iskhakov** [comment]
This functionality will be available in Outgoing Webhooks soon
https://github.com/grafana/oncall/pull/1844
