### ISSUE TITLE
`AlertGroupForAlertManager` matching query does not exist 

### ISSUE THREAD

**Issue by joeyorlando** [grafana/oncall#3728]
### What went wrong?

**What happened**:
We occasionally see failing `apps.alerts.tasks.resolve_alert_group_by_source_if_needed.resolve_alert_group_by_source_if_needed` tasks because of ([logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22jaq%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D~%5C%22%28prod-eu-west-0%7Cprod-us-central-0%7Cops-us-east-0%29%5C%22,%20namespace%3D~%5C%22amixr-%28prod%7Cstaging%29%5C%22%7D%20%7C%3D%20%5C%2244358f90-04cc-45f0-95fb-cd3cfd40c116%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)):

```
`AlertGroupForAlertManager` matching query does not exist 
```

### How do we reproduce it?

Needs further investigation for repro steps

### Grafana OnCall Version

v1.3.90

### Product Area

Alert Flow & Configuration

### Grafana OnCall Platform?

None

**Comment by iskhakov** [comment]
@joeyorlando I can work on that
It happens because create_alert is not atomic and idempotent

it is related to https://github.com/grafana/oncall-private/issues/2208

**Comment by matiasb** [comment]
FWIW, I did a quick check on this one. Right now there is 3 retrying tasks (`44358f90-04cc-45f0-95fb-cd3cfd40c116`, `b7bfe6ae-485f-45e0-9f36-a66110c2ebfa`, `491f75eb-4fdb-4c79-a5ab-4f62c0c7daf8`) that I think could be revoked.

All of them are related to the same alert_group `24150752`, which does not exist (the alerts mentioned in the logs don't exist either, and either the integration isn't there). The alert group seems to have been created on [Dec 9th](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22jaq%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D~%5C%22prod-us-central-0%5C%22,%20namespace%3D~%5C%22amixr-prod%5C%22%7D%20%7C%3D%20%5C%2224150752%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221702129142238%22,%22to%22:%221702131211700%22%7D%7D%7D&orgId=1).

Digging a bit more into logs, it seems the alert group was deleted a few hours later it was received:

`2023-12-09 13:54:47,353 source=engine:celery worker=ForkPoolWorker-27 task_id=a50bdb8c-d8c0-4308-9dda-c8f51a1e80f4 task_name=apps.alerts.tasks.delete_alert_group.delete_alert_group name=apps.alerts.models.alert_group level=DEBUG send alert_group_action_triggered_signal for alert_group 24150752, log record 130160708 with type 'Deleted', action source: delete`

Wondering if the failing task was queued right before the deletion and then it has been retrying since then...

**Comment by matiasb** [comment]
Update: I revoked the retrying tasks per the above.

**Comment by joeyorlando** [comment]
we can probably go ahead and close this issue, it looks like after you revoked the three tasks the retrying has stopped ([logs](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22jaq%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D~%5C%22%28prod-eu-west-0%7Cprod-us-central-0%7Cops-us-east-0%29%5C%22,%20namespace%3D~%5C%22amixr-%28prod%7Cstaging%29%5C%22%7D%20%7C%3D%20%5C%22matching%20query%20does%20not%20exist%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221706639997249%22,%22to%22:%221706725626804%22%7D%7D%7D&orgId=1)). Still doesn't address the root cause that caused it to get into this scenario, but I suppose we can address that if this pops up again?
