### ISSUE TITLE
Inbound submission webhook API should return some identifiers

### ISSUE THREAD

**Issue by mjs** [grafana/oncall#3912]
### What would you like to see!

When an alert is submitted to inbound integration webhook API (i.e. the formatted webhook), the response is simply a plain text `Ok`. This makes it difficult to find the identifying details for the alert via the OnCall API.

We have an internal alerting system where urgent alerts are synchronised to OnCall. The OnCall alert group id is stored in our internal system after the alert has been submitted to OnCall. What we are doing now is quite convoluted:

1. Submit the alert using a formatted webhook call. We include an internal id in the alert details.
2. Make a OnCall alert search API call using the internal id to find the OnCall alert details.
3. Make another OnCall API request to map the alert id to the alert group id. 
4. Store the alert group id against the alert in our internal system.

It would be much more efficient if the formatted webhook API returned the alert id and alert group id at submission time.

### Product Area

Alert Flow & Configuration

**Comment by joeyorlando** [comment]
hi there @mjs 👋

have you considered setting up an Outgoing Webhook with the "Alert Group Created" event type? ([docs](https://grafana.com/docs/oncall/latest/configure/outgoing-webhooks/#alert-group-created))

We don't have any plans to modify the response for incoming alerts. This is because the actual alert creation is done asynchronously. Therefore it is not possible to know these ids at response time.

**Comment by mjs** [comment]
Thanks. I figured this might be what was going on. I'll take a look at Outgoing Webhooks.
