### ISSUE TITLE
Feature Request: Slack Send Alert via Direct Message

### ISSUE THREAD

**Issue by melikesozeri** [grafana/oncall#419]
In Slack integration, it works with message in channel but not in direct message. It only posted alerts in channel, mentioned users in a thread but could not notify users in direct message. 
We want to send alert message via direct message with Slack app. It would be great if DM is supported.

**Comment by melikesozeri** [comment]
:label feauturerequest

**Comment by BitKickerBHS** [comment]
Checking in to see if this is on the roadmap? Being able to send notifications via DM instead of a mention would be a great asset.   I notice Oncall does have the ability to DM in slack I.E. If the mentioned slack user does not have access to the channel the alert is in Oncall will send a DM notifying the user of the access issue.  Does sending a DM go against best practices ?

**Comment by iskhakov** [comment]
closing in favour of https://github.com/grafana/oncall/issues/3874
