### ISSUE TITLE
Allow editing the schedule for sync_organization command

### ISSUE THREAD

**Issue by gavinwoolley** [grafana/oncall#4309]
### What would you like to see!

I'd like to be able to configure the frequency of when the organizations sync from Grafana to Oncall or ideally be able to hit an API to trigger the sync on demand.

### Product Area

Alert Flow & Configuration, Helm, Other

### Anything else to add?

We progamatically manage all of our users, teams, integrations etc 
Currently we have to wait for the users to sync, before we can create integrations that are team scoped, it took 24 hrs yesterday. 
Unless of course we hit the plugin screen, then it syncs. 

We'd like to be able to trigger the sync, or at least configure the frequency of when it happens if possible.

v.1.4.3

**Comment by mderynck** [comment]
Specific to this issue we added an API endpoint to trigger sync on demand (there is a timeout on it so that it does not run more frequently than 5 mins).  You can use a service account token as well to call this (see Grafana docs).  Also note this caches a copy locally and it will not send anything to the OnCall backend if it does not detect any changes.
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/sync'
```

Recently we made some changes to the way Grafana OnCall is initialized.  Use 1.9.22, there were quite a few changes along the way from 1.9.0-1.9.22 to get things working.
- If you are running Grafana 11 and newer you must have `externalServiceAccounts` feature toggle enabled.
This has already been enabled in the docker compose files and helm charts in the oncall repo.
- Plugin settings must be provided to the plugin using an API call if you are installing for the first time (Note: credentials and hostnames need to be adjusted for your configuration, stackId and orgId are expected to be the listed constants in a self-hosted configuration)
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/settings' -H "Content-Type: application/json" -d '{"enabled":true, "jsonData":{"stackId":5, "orgId":100, "onCallApiUrl":"http://engine:8080/", "grafanaUrl":"http://grafana:3000/"}}'
```
- Once settings are configured use this API call to install:
```
curl -X POST 'http://admin:admin@localhost:3000/api/plugins/grafana-oncall-app/resources/plugin/install'
```
Grafana OnCall should now be ready to use.
For additional troubleshooting see [here](https://github.com/grafana/oncall#troubleshooting)
