### ISSUE TITLE
Schedules: Allow web-edited overrides for Terraform-managed rotations

### ISSUE THREAD

**Issue by Matvey-Kuk** [grafana/oncall#828]
Managing "basic" rotation in Terraform is comfortable but making overrides is tricky (users need to do it fast). I'm thinking about allowing web-based overrides for TF-generated schedules. Any thoughts?

**Comment by mem** [comment]
The use case we have is we have an schedule defined in Terraform that provides the primary rotation, and an iCal source that provides the overrides. When we add or remove people from the rotation, this is straightforward to do in Terraform (add / remove line, possibly reorder entries). But the iCal source for the overrides can become a little confusing, specially when dealing with shifts that span multiple days (Google Calendar falls back to displaying those at the top of the day instead of regular block _in_ the day).

So what we would ideally like to do is define the schedule in Terraform and be able to use the web interface to edit overrides. We _do_ take advantage of levels ([L1], [L2], etc) in the iCal entries. One case is a situation where the team is having an offsite, so we define overrides for the duration of the offsite and return to the regular rotation after that. But during the offsite we might still need to add small overrides so that the incident gets routed to a different person or team.

**Comment by SMR39** [comment]
@Matvey-Kuk I think this would be amazing to be able to override via UI instead of creating a PR to override via terraform. 

Any ETA on this ?

**Comment by Matvey-Kuk** [comment]
This issue was included in the core-team's short term backlog. No strict ETA, will keep you informed.

**Comment by vadimkerr** [comment]
Overriding Terraform schedules implemented in https://github.com/grafana/oncall/pull/1222
