### ISSUE TITLE
User notification settings with "Wait" steps can be ignored if escalation chains have new events before the "Wait" completes

### ISSUE THREAD

**Issue by erik-hunter** [grafana/oncall#934]
I configured my notification settings like this:
![Screen Shot 2022-12-01 at 10 50 37 AM](https://user-images.githubusercontent.com/5383873/205124680-9b1f19db-b22e-4a7a-a67f-d16813e513b0.png)

And the escalation chain looks like this:
![Screen Shot 2022-12-01 at 10 51 18 AM](https://user-images.githubusercontent.com/5383873/205124806-34423774-e935-47db-bcf4-ec1ce330cd30.png)

You can see that I never recieved a call, since the escalation chain begins a new step.
![Screen Shot 2022-12-01 at 10 52 07 AM](https://user-images.githubusercontent.com/5383873/205124960-14076e19-7abf-447f-9c01-7fd78b9afb3d.png)

Shouldn't the user's notifications be executed to completion - regardless of whether a new escalation chain step has started?

Thanks!

**Comment by Alb0t** [comment]
> Hi! In this case OnCall behaves as expected. If we make OnCall to finish personal notification chains even when the next escalation chain step will begin, we'll continue pinging 2,3,4 people in parallel. The purpose of OnCall is to ping one person at a time until other behaviour is set explicitly in schedules or escalation chains.

If this is the expected behavior, can the tool at a minimum notify a user making the configuration that there are unreachable steps? I do not want users to accidentally configure their profile and their group in a way that leads them to never receive a notification. This should not be an acceptable configuration without at least a warning, as it will lead to outages.
